// caseContext — the dynamic training-case shape generated by /api/generate-case.
// Also provides a fallback (the original 不锈钢保温杯 → 德国 case) so the app
// always works even when the LLM endpoint is unavailable.

/**
 * @typedef {Object} CaseContext
 * @property {Array<{name:string,mandatory:boolean,body:string,region:string,note:string}>} requiredCerts
 * @property {string} hsCodeRange
 * @property {string} tariffNotes
 * @property {string} culturalNotes
 * @property {string[]} commonPitfalls
 * @property {Object} buyerPersona
 * @property {string} buyerPersona.name
 * @property {string} buyerPersona.company
 * @property {string} buyerPersona.city
 * @property {string} buyerPersona.country
 * @property {string} buyerPersona.role
 * @property {string} buyerPersona.background
 * @property {string} buyerPersona.style
 * @property {string} buyerPersona.language
 * @property {string} initialInquiryEmail
 * @property {string} supplierProfileHint
 * @property {Object} pricingBaseline
 */

/** Hardcoded fallback used when LLM generation fails or hasn't run yet. */
export const FALLBACK_CASE = {
  requiredCerts: [
    {
      name: 'LFGB',
      mandatory: true,
      body: 'BfR (Germany)',
      region: 'Germany',
      note: '德国食品接触材料法，不通过无法销售',
    },
    {
      name: 'CE',
      mandatory: true,
      body: 'European Commission',
      region: 'EU',
      note: '欧盟产品合规标识',
    },
    {
      name: 'FDA',
      mandatory: false,
      body: 'US FDA',
      region: 'USA',
      note: '美国市场需补充',
    },
  ],
  hsCodeRange: '7323.93.x for stainless steel kitchenware',
  tariffNotes: '德国进口关税约 3.7%（基于 CIF），无反倾销',
  culturalNotes: '德国买家重合规、重数据、回信慢但下单快；忌价格战话术',
  commonPitfalls: [
    'LFGB 缺失 → 德国海关扣货',
    '不报贸易条款 → 买家无法核算落地价',
    '盲目让价 → 买家持续压价',
  ],
  buyerPersona: {
    name: 'Michael Braun',
    company: 'Braun Kitchenware GmbH',
    city: 'Hamburg',
    country: 'Germany',
    role: 'Procurement Manager',
    background: '8 years in kitchenware import, focus on EU compliance',
    style: 'professional, polite, tough on price, values authenticity',
    language: 'English',
  },
  initialInquiryEmail:
    "Hello,\n\nI found your vacuum flask on Alibaba. We are a kitchenware importer based in Hamburg, Germany. We're interested in ordering 500–1000 pcs per month.\n\nCould you please send us:\n1. Product specifications (capacity, material, weight)\n2. Your best FOB price for 500 pcs\n3. Lead time and MOQ\n4. Any certifications (CE, LFGB, etc.)\n\nLooking forward to your reply.\n\nBest regards,\nMichael Braun\nBraun Kitchenware GmbH",
  supplierProfileHint: '广东/浙江为主，需 LFGB 支持',
  pricingBaseline: {
    factoryPriceCNY: [25, 40],
    moqRange: [300, 1000],
    marginAdvice: '初始利润率建议 25-30%，留足谈判缓冲',
  },
};

/**
 * Validate a generated caseContext, fill missing fields with fallback values.
 * Never throws — returns something usable.
 */
export function normalizeCaseContext(raw) {
  if (!raw || typeof raw !== 'object') return FALLBACK_CASE;
  const f = FALLBACK_CASE;
  return {
    requiredCerts: Array.isArray(raw.requiredCerts) && raw.requiredCerts.length
      ? raw.requiredCerts
      : f.requiredCerts,
    hsCodeRange: raw.hsCodeRange || f.hsCodeRange,
    tariffNotes: raw.tariffNotes || f.tariffNotes,
    culturalNotes: raw.culturalNotes || f.culturalNotes,
    commonPitfalls: Array.isArray(raw.commonPitfalls) && raw.commonPitfalls.length
      ? raw.commonPitfalls
      : f.commonPitfalls,
    buyerPersona: { ...f.buyerPersona, ...(raw.buyerPersona || {}) },
    initialInquiryEmail: raw.initialInquiryEmail || f.initialInquiryEmail,
    supplierProfileHint: raw.supplierProfileHint || f.supplierProfileHint,
    pricingBaseline: { ...f.pricingBaseline, ...(raw.pricingBaseline || {}) },
  };
}

/** Get the active case context from state, falling back to default if not yet generated. */
export function getActiveCase(state) {
  return state?.caseContext || FALLBACK_CASE;
}
