// stageMaterials — case-specific seed data for every stage (suppliers, HS quiz, QC items, etc.)
// Generated by /api/generate-stage-materials. Falls back to FALLBACK_MATERIALS (kitchenware/Germany)
// if generation fails or hasn't run yet.

/** Original hardcoded data, used as fallback. Mirrors v2's hardcoded Stage 2/7/8/9 content. */
export const FALLBACK_MATERIALS = {
  suppliers: [
    {
      id: 'sup_a',
      name: '义乌恒温制品厂',
      city: '义乌',
      factoryPriceCNY: 28,
      moq: 500,
      sampleFee: 80,
      certSupport: false,
      qcCapability: 'third-party',
      leadTimeDays: 30,
      profileNote: '价格优势但缺 LFGB 认证',
    },
    {
      id: 'sup_b',
      name: '深圳优杯科技有限公司',
      city: '深圳',
      factoryPriceCNY: 32,
      moq: 300,
      sampleFee: 120,
      certSupport: true,
      qcCapability: 'in-house',
      leadTimeDays: 25,
      profileNote: 'LFGB 支持 + 自有 QC',
    },
  ],
  hsCodeQuiz: {
    question: '你正在出口不锈钢保温杯（500ml，双层真空，无电子元件）。以下哪个 HS 编码最准确？',
    options: [
      { code: '3924.10.00', name: '塑料餐具及厨房用具', correct: false, explanation: '塑料制品编码，不适用不锈钢' },
      { code: '7323.93.90', name: '不锈钢家用器皿', correct: true, explanation: '正确：金属制家用器皿 + 不锈钢细分' },
      { code: '8418.99.00', name: '制冷设备及零件', correct: false, explanation: '保温杯无机械制冷功能，不适用' },
      { code: '4419.90.00', name: '木制餐具', correct: false, explanation: '木制品编码，不适用' },
    ],
  },
  qcChecklist: [
    {
      id: 'qc_1',
      label: 'Logo 公差',
      description: '激光雕刻 Logo 偏移检查（标准 ±0.5mm）',
      riskLevel: 'medium',
      factoryToleranceClaim: '3mm 偏移在行业可接受范围',
    },
    {
      id: 'qc_2',
      label: 'LFGB 标签',
      description: '认证标签印刷清晰度 + 编号有效性',
      riskLevel: 'high',
      factoryToleranceClaim: '标签位置略偏不影响合规',
    },
    {
      id: 'qc_3',
      label: '热感测试',
      description: '100℃ 水保温 6 小时温度衰减',
      riskLevel: 'high',
      factoryToleranceClaim: '当前批次性能符合规格书',
    },
  ],
  blFields: [
    { label: 'Consignee', value: 'Braun Kitchenwere GmbH', isError: true, errorType: 'spelling' },
    { label: 'HS Code', value: '3924.10.00', isError: true, errorType: 'mismatch' },
    { label: 'Port of Loading', value: 'Shenzhen, China', isError: false, errorType: null },
    { label: 'Port of Discharge', value: 'Hamburg, Germany', isError: false, errorType: null },
    { label: 'Quantity / Description', value: '500 PCS Stainless Steel Vacuum Flask 500ml', isError: false, errorType: null },
  ],
  complaintScenario: {
    issueType: '色差',
    issueDetailEn:
      'Hi, we received the shipment last week. Out of 500 pieces, 30 show noticeable color variation in the matte coating — much darker than the approved sample. Our retail buyer is upset. We need to discuss compensation.',
    sampleData: '500 件中 30 件出现色差，6%',
    factoryLeverageGood: '工厂同意补发，承担物流费',
    factoryLeverageBad: '工厂以"QC 已接受公差"为由拒绝补发，要求平摊费用',
  },
  piDefaults: {
    productDesc: '不锈钢保温杯 500ml，双层真空，304不锈钢，BPA-free',
    spec: 'Ø70×H220mm, 280g, 304 stainless steel inner & outer',
  },
  stage3Hints: {
    openingExamples: [
      'Hi {name}, I saw your kitchenware import range and noticed your focus on EU-compliant products...',
      'Dear {name}, our LFGB-certified vacuum flask line may complement your existing thermos category...',
      'Hello {name}, given your Hamburg market, I thought our 304 SS / BPA-free thermos with 12-color customization could be relevant...',
    ],
    valuePropExamples: [
      'LFGB cert valid till 2027, 304 SS double-wall, MOQ 500.',
      '12-color matte powder coating, 200ml/350ml/500ml capacities.',
      'Direct factory, OEM logo welcome, sample lead-time 7 days.',
    ],
  },
  stage4ReadingGate: [
    { id: 'rg_1', label: '产品规格（容量/材质/重量）' },
    { id: 'rg_2', label: 'FOB 价格（500 件）' },
    { id: 'rg_3', label: '交期 + MOQ' },
    { id: 'rg_4', label: '认证（CE / LFGB）' },
  ],
  shipmentNotifyRubric: {
    dimensions: [
      { key: 'tracking', label: '追踪号 / B/L 引用' },
      { key: 'balance', label: '尾款金额明确' },
      { key: 'deadline', label: '付款截止具体日期' },
      { key: 'thermal', label: '保温品质提示' },
    ],
  },
  repurchaseRubric: {
    dimensions: [
      { key: 'newProduct', label: '新品 / 系列引导' },
      { key: 'urgency', label: '紧迫感 / 季节钩' },
      { key: 'personalization', label: '个性化称呼' },
      { key: 'loyalty', label: '忠诚度激励' },
    ],
  },
};

/**
 * Validate / sanitize raw materials from /api/generate-stage-materials,
 * filling in missing pieces with FALLBACK_MATERIALS so consumers can rely on shape.
 */
export function normalizeStageMaterials(raw) {
  if (!raw || typeof raw !== 'object') return FALLBACK_MATERIALS;
  const f = FALLBACK_MATERIALS;
  return {
    suppliers:
      Array.isArray(raw.suppliers) && raw.suppliers.length === 2
        ? raw.suppliers.map((s, i) => ({
            id: s.id || (i === 0 ? 'sup_a' : 'sup_b'),
            name: s.name || f.suppliers[i].name,
            city: s.city || f.suppliers[i].city,
            factoryPriceCNY: Number(s.factoryPriceCNY) || f.suppliers[i].factoryPriceCNY,
            moq: Number(s.moq) || f.suppliers[i].moq,
            sampleFee: Number(s.sampleFee) || f.suppliers[i].sampleFee,
            certSupport: !!s.certSupport,
            qcCapability: s.qcCapability || f.suppliers[i].qcCapability,
            leadTimeDays: Number(s.leadTimeDays) || f.suppliers[i].leadTimeDays,
            profileNote: s.profileNote || f.suppliers[i].profileNote,
          }))
        : f.suppliers,
    hsCodeQuiz:
      raw.hsCodeQuiz?.options?.length === 4
        ? {
            question: raw.hsCodeQuiz.question || f.hsCodeQuiz.question,
            options: raw.hsCodeQuiz.options.map((o) => ({
              code: o.code || '',
              name: o.name || '',
              correct: !!o.correct,
              explanation: o.explanation || '',
            })),
          }
        : f.hsCodeQuiz,
    qcChecklist:
      Array.isArray(raw.qcChecklist) && raw.qcChecklist.length === 3
        ? raw.qcChecklist.map((q, i) => ({
            id: q.id || `qc_${i + 1}`,
            label: q.label || f.qcChecklist[i].label,
            description: q.description || f.qcChecklist[i].description,
            riskLevel: q.riskLevel || f.qcChecklist[i].riskLevel,
            factoryToleranceClaim:
              q.factoryToleranceClaim || f.qcChecklist[i].factoryToleranceClaim,
          }))
        : f.qcChecklist,
    blFields:
      Array.isArray(raw.blFields) && raw.blFields.length === 5
        ? raw.blFields.map((b, i) => ({
            label: b.label || f.blFields[i].label,
            value: b.value || f.blFields[i].value,
            isError: !!b.isError,
            errorType: b.errorType || null,
          }))
        : f.blFields,
    complaintScenario: { ...f.complaintScenario, ...(raw.complaintScenario || {}) },
    piDefaults: { ...f.piDefaults, ...(raw.piDefaults || {}) },
    stage3Hints: { ...f.stage3Hints, ...(raw.stage3Hints || {}) },
    stage4ReadingGate:
      Array.isArray(raw.stage4ReadingGate) && raw.stage4ReadingGate.length === 4
        ? raw.stage4ReadingGate
        : f.stage4ReadingGate,
    shipmentNotifyRubric: raw.shipmentNotifyRubric?.dimensions
      ? raw.shipmentNotifyRubric
      : f.shipmentNotifyRubric,
    repurchaseRubric: raw.repurchaseRubric?.dimensions
      ? raw.repurchaseRubric
      : f.repurchaseRubric,
  };
}

/** Read active materials from state with safe fallback. */
export function getActiveMaterials(state) {
  return state?.stageMaterials || FALLBACK_MATERIALS;
}
